[project]
name = "pyergonomics"
version = "0.1.0"
description = "pose analysis with python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bokeh>=3.8.0",
    "bvhtoolbox>=0.1.3",
    "ipycanvas>=0.14.1",
    "jupyter>=1.1.1",
    "k3d>=2.17.0",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "polars>=1.35.1",
    "pose-skeletons",
    "toml>=0.10.2",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyergonomics",
]

[tool.uv.sources]
pyergonomics = { workspace = true }
pose-skeletons = { path = "../pose_skeletons", editable = true }

[project.scripts]
init-project = "pyergonomics:init_project"

